# Create AD Computer Object

- name: AD Create
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create AD Record
    onefuse:
     policy_name: '{{ policy_name }}'
     module: ad
     state: present
     name: '{{ onefuse_name_machine.name }}'
     tracking_id: '{{ onefuse_name_machine.trackingId  | default(omit) }}'
     template_properties: '{{ template_properties }}'
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
         onefuse_ad: '{{ onefuse_ad }}'



