- name: Machine Name
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get Machine Name
    onefuse:
      policy_name: '{{ policy_name }}'
      module: naming
      state: present
      tracking_id: '{{ tracking_id  | default(omit) }}'
      template_properties: '{{ template_properties }}'
    delegate_to: localhost
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
          onefuse_name: '{{ onefuse_name }}'




