# Create AD Computer Object

- name: Create ServiceNow CMDB Record
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create CMDB CI Record
    onefuse:
     policy_name: '{{ policy_name }}'
     module: cmdb
     state: present
     tracking_id: '{{ onefuse_name.trackingId  | default(omit) }}'
     template_properties: {
      OneFuse_VmNic0.dnsSuffix: '{{ onefuse_ipam.dnsSuffix }}',
      OneFuse_VmNic0.hostname: '{{ onefuse_ipam.hostname }}',
      OneFuse_VmNic0.fqdn: '',
      OneFuse_VmNic0.ipAddress: '{{ onefuse_ipam.ipAddress }}',
      OneFuse_VmHardware.platformUuid: '',
      OneFuse_VmHardware.cpuCount: '2',
      OneFuse_VmHardware.totalStorageGB: '16',
      OneFuse_VmHardware.memoryMB: '1024',
      OneFuse_VmHardware.powerState: 'on'
     }
    delegate_to: localhost
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
         onefuse_cmdb: '{{ onefuse_cmdb }}'