- name: OneFuse DNS
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Register DNS
    onefuse:
      policy_name: '{{ dns_policy_name }}'
      module: dns
      state: present
      name: '{{ onefuse_name.name }}'
      value: '{{ onefuse_ipam.ipAddress }}'
      zones: '{{ onefuse_ipam.dnsSuffix }}'
      tracking_id: '{{ onefuse_name.trackingId | default(omit) }}'
      template_properties: '{{ template_properties }}'
    delegate_to: localhost
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
         onefuse_dns: '{{ onefuse_dns }}'