# Deploy vRA Blueprint

- name: Deploy vRA
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy vRA Blueprint
    onefuse:
     policy_name: '{{ policy_name }}'
     deployment_name: '{{ onefuse_name_deployment.name }}'
     module: vra
     state: present
     tracking_id: '{{ onefuse_name.trackingId  | default(omit) }}'
     template_properties: '{{ template_properties }}'
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
         onefuse_vra: '{{ onefuse_vra }}'