# Run Ansible Tower Job

- name: OneFuse Ansible Tower
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Run Ansible Tower Playbook
    onefuse:
      policy_name: '{{ policy_name }}'
      module: ansible_tower
      state: present
      limit: ''
      hosts: ''
      tracking_id: '{{ onefuse_name.trackingId  | default(omit) }}'
      template_properties: {
       nameGroup: 'pp',
       nameLocation: 'atl',
       nameEnv: 'p',
       nameOS: 'l',
       nameApp: 'wp'
        }
    delegate_to: localhost
    register: output
  - name: Output Results
    debug:
      msg: '{{ output }}'
  - name: "Pass Output to workflow"
    set_stats:
        data:
         onefuse_ansible_tower: '{{ onefuse_ansible_tower }}'