- name: OneFuse Scripting
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Execute Script
    onefuse:
      policy_name: '{{ policy_name }}'
      module: scripting
      state: present
      tracking_id: '{{ onefuse_name.trackingId  | default(omit) }}'
      template_properties: '{{ template_properties }}'
    delegate_to: localhost
    register: output
 



