# Create host in Ansible Inventory
- name: Create Ansible Host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add Host to Tower Inventory
      tower_host:
        name: '{{ onefuse_ipam.hostname | default(omit) }}'
        inventory: 'onefuse'
        state: present
        tower_username: admin
        tower_password: VmwareS0v
        tower_host: https://localhost
        validate_certs: no
        variables:
          onefuse_name_machine: '{{ onefuse_name_machine | default(omit) }}'
          onefuse_name_deployment: '{{ onefuse_name_deployment| default(omit)  }}'
          onefuse_dns: '{{ onefuse_dns | default(omit) }}'
          onefuse_cmdb: '{{ onefuse_cmdb | default(omit) }}'
          onefuse_script: '{{ onefuse_script| default(omit) }}'
          onefuse_ansible_tower: '{{ onefuse_ansible_tower | default(omit) }}'
          onefuse_vra: '{{ onefuse_vra | default(omit)  }}'
          vsphere_vm: '{{ vm_output | default(omit) }}'