- name: OneFuse Ansible Wrapper
  hosts: localhost
  gather_facts: false
  tasks:  
  - name: Launch Workflow
    tower_workflow_launch:
      workflow_template: "{{ ansible_workflow_template }}"
      extra_vars:
        policy_name: '{{ policy_name }}'
        tracking_id: '{{ tracking_id | default(omit) }}'
        template_properties: '{{ template_properties }}'
      tower_username: admin
      tower_password: VmwareS0v
      tower_host: https://localhost
      validate_certs: no
    delegate_to: localhost
