- name: OneFuse Ansible Wrapper
  hosts: localhost
  gather_facts: false
  tasks:  
  - name: Launch Workflow
    tower_workflow_launch:
      workflow_template: "{{ ansible_workflow_template }}"
      tower_username: admin
      tower_password: VmwareS0v
      tower_host: https://localhost
      validate_certs: no
      wait: False
    delegate_to: localhost
